apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-detail
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      app: catalog-detail
      version: v1
  template:
    metadata:
      labels:
        app: catalog-detail
        version: v1
    spec:
      containers:
        - name: catalog-detail
          image: catalog-detail-service:v1
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
